config/routes.rb
Couriertrack::Application.routes.draw do

  resources :searches, :user_sessions, :courier_sessions, :users
  
  match 'courier_login' => 'courier_sessions#new', :as => :courier_login
  match 'courier_logout' => 'courier_sessions#destroy', :as => :courier_logout
  
  match 'user_login' => 'user_sessions#new', :as => :user_login
  match 'user_logout' => 'user_sessions#destroy', :as => :user_logout

  resources :couriers do
  	resources :deliveries do
  		resources :dropoffs
  		resources :pickups
  	end
  end

end

app/models/pickup.rb
class Pickup < ActiveRecord::Base
	acts_as_mappable :default_units => :kms, :auto_geocode=>{:field=>:pickup_address, :error_message=>'Could not geocode address'}
	belongs_to :delivery
	
	validates_presence_of :pickup_address, :pickup_name
	validates_datetime :pickup_after, :after => DateTime.now
	validates_datetime :pickup_after, :before => self.delivery.delivery_due
	
end

app/controllers/pickups_controller.rb
class PickupsController < ApplicationController
  # GET /pickups
  # GET /pickups.xml
  def index
  	@courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:delivery_id])
    @pickups = @delivery.pickups.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pickups }
    end
  end

  # GET /pickups/1
  # GET /pickups/1.xml
  def show
    @courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:delivery_id])
    @pickup = @delivery.pickups.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pickup }
    end
  end

  # GET /pickups/new
  # GET /pickups/new.xml
  def new
    @courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:delivery_id])
    @pickup = @delivery.pickups.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pickup }
    end
  end

  # GET /pickups/1/edit
  def edit
    @courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:delivery_id])
    @pickup = @delivery.pickups.find(params[:id])
  end

  # POST /pickups
  # POST /pickups.xml
  def create
    @courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:delivery_id])
    @pickup = @delivery.pickups.new(params[:pickup])

    respond_to do |format|
      if @pickup.save
        format.html { redirect_to(courier_delivery_dropoffs_path(@courier, @delivery), :notice => 'Pickup was successfully created.') }
        format.xml  { render :xml => @pickup, :status => :created, :location => @pickup }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pickup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pickups/1
  # PUT /pickups/1.xml
  def update
  	@courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:delivery_id])
    @pickup = @delivery.pickups.find(params[:id])

    respond_to do |format|
      if @pickup.update_attributes(params[:pickup])
        format.html { redirect_to(@pickup, :notice => 'Pickup was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pickup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pickups/1
  # DELETE /pickups/1.xml
  def destroy
    @courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:delivery_id])
    @pickup = @delivery.pickups.find(params[:id])
    @pickup.destroy

    respond_to do |format|
      format.html { redirect_to(pickups_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/views/pickups/_form.html.erb
<%= form_for(@pickup) do |f| %>
  <% if @pickup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pickup.errors.count, "error") %> prohibited this pickup from being saved:</h2>

      <ul>
      <% @pickup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pickup_address %><br />
    <%= f.text_field :pickup_address %>
  </div>
  <div class="field">
    <%= f.label :pickup_name %><br />
    <%= f.text_field :pickup_name %>
  </div>
  <div class="field">
    <%= f.label :pickup_after %><br />
    <%= f.datetime_select :pickup_after %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pickups/edit.html.erb
<h1>Editing pickup</h1>

<%= render 'form' %>

<%= link_to 'Show', courier_delivery_pickup_path(@courier, @delivery, @pickup) %> |
<%= link_to 'Back', courier_delivery_pickups_path %>

app/views/pickups/index.html.erb
<h1>Listing pickups</h1>

<table>
  <tr>
    <th>Pickup address</th>
    <th>Pickup name</th>
    <th>Pickup after</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pickups.each do |pickup| %>
  <tr>
    <td><%= pickup.pickup_address %></td>
    <td><%= pickup.pickup_name %></td>
    <td><%= pickup.pickup_after %></td>
    <td><%= link_to 'Show', courier_delivery_pickup_path(@courier, @delivery, pickup) %></td>
    <td><%= link_to 'Edit', edit_courier_delivery_pickup_path(@courier, @delivery, pickup) %></td>
    <td><%= link_to 'Destroy', [@courier, @delivery, pickup], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dropoff', new_courier_delivery_pickup_path(@courier, @delivery) %>

app/views/pickups/new.html.erb
<h1>New pickup</h1>

<%= render 'form' %>

<%= link_to 'Back', courier_delivery_pickups_path(@courier, @delivery) %>

app/views/pickups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pickup address:</b>
  <%= @pickup.pickup_address %>
</p>

<p>
  <b>Pickup name:</b>
  <%= @pickup.pickup_name %>
</p>

<p>
  <b>Pickup after:</b>
  <%= @pickup.pickup_after %>
</p>


<%= link_to 'Edit', edit_courier_delivery_pickup_path(@courier, @delivery, @pickup) %> |
<%= link_to 'Back', courier_delivery_pickups_path %>