config/routes.rb
Couriertrack::Application.routes.draw do

  resources :searches, :user_sessions, :courier_sessions, :users
  
  match 'courier_login' => 'courier_sessions#new', :as => :courier_login
  match 'courier_logout' => 'courier_sessions#destroy', :as => :courier_logout
  
  match 'user_login' => 'user_sessions#new', :as => :user_login
  match 'user_logout' => 'user_sessions#destroy', :as => :user_logout

  resources :couriers do
  	resources :deliveries do
  		resources :dropoffs
  		resources :pickups
  	end
  end

end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
	belongs_to :courier
	belongs_to :search
	has_one :pickup, :dependent => :destroy
	has_one :dropoff, :dependent => :destroy
	
	validates_numericality_of :number_of_packages, :greater_than_or_equal_to => 1, :only_integer => true
	validates_numericality_of :mass, :volume, :greater_than_or_equal_to => 0.01
	
	#def calc_earliest_delivery_time
	#	last_delivery = self.courier.deliveries.where(:successfully_delivered => false).order('waypoint_order DESC').first
	#	if last_delivery.nil?
	#		directions = GoogleDirections.new(false, self.courier.transport_mode, "#{self.courier.lat} #{self.courier.lng}", pickup_address)
	#		earliest_delivery_time = DateTime.now + directions.drive_time_in_minutes.minutes
	#	else
	#		# TODO rather than .delivery_due calc time for whole route just in case courier is running late
	#		directions = GoogleDirections.new(false, self.courier.transport_mode, last_delivery.dropoff_address, pickup_address)
	#	end
	#	earliest_delivery_time
	#end
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  # GET /deliveries
  # GET /deliveries.xml
  def index
  	@courier = Courier.find(params[:courier_id])
    @deliveries = @courier.deliveries.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @deliveries }
    end
  end

  # GET /deliveries/1
  # GET /deliveries/1.xml
  def show
  	@courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @delivery }
    end
  end

  # GET /deliveries/new
  # GET /deliveries/new.xml
  def new
  	@courier = Courier.find(params[:courier_id])
    if params[:search_id]
    	search = Search.find(params[:search_id])
    	@delivery = @courier.deliveries.build(:pickup_address => search.pickup_address, :mass => search.min_mass, :volume => search.min_volume, :delivery_due => search.delivery_due)
    else
    	@delivery = @courier.deliveries.build
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @delivery }
    end
  end

  # GET /deliveries/1/edit
  def edit
  	@courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:id])
  end

  # POST /deliveries
  # POST /deliveries.xml
  def create
  	@courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.build(params[:delivery])
    @courier.add_delivery_mass_and_volume(@delivery)

    respond_to do |format|
      if @delivery.valid? & @courier.valid?
      	Delivery.transaction do
      		@courier.save!
      		@delivery.save!
      		format.html { redirect_to(courier_delivery_pickups_path(@courier, @delivery), :notice => 'Delivery was successfully created.') }
        	format.xml  { render :xml => @delivery, :status => :created, :location => @delivery }
      	end
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @delivery.errors + @courier.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /deliveries/1
  # PUT /deliveries/1.xml
  def update
  	@courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:id])
    @courier.remove_delivery_mass_and_volume(@delivery)
    @delivery.attributes = params[:delivery] # rather than update_attributes so not saved until transaction
    @courier.add_delivery_mass_and_volume(@delivery)

    respond_to do |format|
      if @delivery.valid? & @courier.valid?
      	Delivery.transaction do
      		@courier.save!
      		@delivery.save!
      		format.html { redirect_to(courier_delivery_path(@courier, @delivery), :notice => 'Delivery was successfully updated.') }
        	format.xml  { head :ok }
      	end
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @delivery.errors + @courier.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /deliveries/1
  # DELETE /deliveries/1.xml
  def destroy
  	@courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:id])
    @courier.remove_delivery_mass_and_volume(@delivery)
    @delivery.destroy

    respond_to do |format|
      format.html { redirect_to(courier_deliveries_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/views/deliveries/_form.html.erb
<%= form_for([@courier, @delivery]) do |f| %>
  <% if @delivery.errors.any? or @courier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@delivery.errors.count + @courier.errors.count, "error") %> prohibited this delivery from being saved:</h2>

      <ul>
      <% all_errors = @delivery.errors.full_messages + @courier.errors.full_messages %>
      <% all_errors.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number_of_packages %><br />
    <%= f.text_field :number_of_packages %>
  </div>
  <div class="field">
    <%= f.label :mass %><br />
    <%= f.text_field :mass %>
  </div>
  <div class="field">
    <%= f.label :volume %><br />
    <%= f.text_field :volume %>
  </div>
  <div class="field">
    <%= f.label :successfully_delivered %><br />
    <%= f.check_box :successfully_delivered %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deliveries/edit.html.erb
<h1>Editing delivery</h1>

<%= render 'form' %>

<%= link_to 'Show', courier_delivery_path(@courier, @delivery) %> |
<%= link_to 'Back', courier_deliveries_path %>

app/views/deliveries/index.html.erb
<h1>Listing deliveries</h1>

<table>
  <tr>
    <th>Number of packages</th>
    <th>Mass</th>
    <th>Volume</th>
    <th>Delivery due</th>
    <th>Succesfully delivered</th>
    <th>Pickup</th>
    <th>Dropoff</th>
  </tr>

<% @deliveries.each do |delivery| %>
  <tr>
    <td><%= delivery.number_of_packages %></td>
    <td><%= delivery.mass %></td>
    <td><%= delivery.volume %></td>
    <td><%= delivery.delivery_due %></td>
    <td><%= delivery.successfully_delivered %></td>
    <td><%= if delivery.pickup.nil?
    			link_to 'Create Pickup', new_courier_delivery_pickup_path(@courier, delivery)
	    	else
	    		link_to 'Show Pickup', courier_delivery_pickup_path(@courier, delivery, delivery.pickup)
	    	end %></td>
    <td><%= if delivery.dropoff.nil?
    			link_to 'Create Dropoff', new_courier_delivery_dropoff_path(@courier, delivery)
	    	else
	    		link_to 'Show Dropoff', courier_delivery_dropoff_path(@courier, delivery, delivery.dropoff)
	    	end %></td>
    <td><%= link_to 'Show', courier_delivery_path(@courier, delivery) %></td>
    <td><%= link_to 'Edit', edit_courier_delivery_path(@courier, delivery) %></td>
    <td><%= link_to 'Destroy', [@courier, delivery], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Delivery', new_courier_delivery_path(@courier) %>

app/views/deliveries/new.html.erb
<h1>New delivery</h1>

<%= render 'form' %>

<%= link_to 'Back', courier_deliveries_path(@courier) %>

app/views/deliveries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pickup address:</b>
  <%= @delivery.pickup_address %>
</p>

<p>
  <b>Pickup name:</b>
  <%= @delivery.pickup_name %>
</p>

<p>
  <b>Dropoff address:</b>
  <%= @delivery.dropoff_address %>
</p>

<p>
  <b>Dropoff name:</b>
  <%= @delivery.dropoff_name %>
</p>

<p>
  <b>Number of packages:</b>
  <%= @delivery.number_of_packages %>
</p>

<p>
  <b>Mass:</b>
  <%= @delivery.mass %>
</p>

<p>
  <b>Volume:</b>
  <%= @delivery.volume %>
</p>

<p>
  <b>Delivery due:</b>
  <%= @delivery.delivery_due %>
</p>

<p>
  <b>Courier:</b>
  <%= @delivery.courier_id %>
</p>

<p>
  <b>Successfully delivered:</b>
  <%= @delivery.successfully_delivered %>
</p>


<%= link_to 'Edit', edit_courier_delivery_path(@courier, @delivery) %> |
<%= link_to 'Back', courier_deliveries_path %>