config/routes.rb
Couriertrack::Application.routes.draw do

  resources :searches, :user_sessions, :courier_sessions, :users
  
  match 'courier_login' => 'courier_sessions#new', :as => :courier_login
  match 'courier_logout' => 'courier_sessions#destroy', :as => :courier_logout
  
  match 'user_login' => 'user_sessions#new', :as => :user_login
  match 'user_logout' => 'user_sessions#destroy', :as => :user_logout

  resources :couriers do
  	resources :deliveries do
  		resources :dropoffs
  		resources :pickups
  	end
  end

end

app/models/search.rb
class Search < ActiveRecord::Base
	
	has_many :search_couriers, :dependent => :destroy
	has_many :deliveries
	
	validates_numericality_of :min_volume, :min_mass, :total_cost_less_than, :max_distance, :greater_than_or_equal_to => 0.01
	validates_presence_of :pickup_address, :transport_mode
	validates_datetime :delivery_due, :after => DateTime.now
	validates_datetime :last_coordinate_update_time_greater_than, :before => DateTime.now
	validate :geocode_address, :if => :pickup_address
	
	MAX_DISTANCES = [ 1, 2, 5, 10, 20, 50 ]
	
	def couriers
	  @couriers ||= find_couriers_within_distance
	  @couriers = find_couriers(@couriers)
	end
	
	def geocode_address
		pickup_loc = GeoKit::Geocoders::MultiGeocoder.geocode(pickup_address)
		errors.add(:pickup_address, "Unable to geocode your location from Pickup Address entered.") unless pickup_loc.success
	end
	
	private
	
	def new_search_courier(courier)
		search_courier = SearchCourier.new
		search_courier.courier_id = courier.id
		search_courier.search_id = id
		search_courier
	end
	
	def estimate_delivery_datetime(courier, dist)
		kph = case courier.transport_mode
			when "Bicycle" then 32
			when "Car", "Truck" then 64
			else 5
		end
		earliest_delivery = (dist/kph).hours
		if courier.deliveries.nil?
			earliest_delivery += DateTime.now
		else
			last_delivery = courier.deliveries.find(:all, successfully_delivered => false).order('waypoint_order DESC').first
			earliest_delivery = last_delivery.delivery_due + earliest_delivery
		end
		earliest_delivery
	end
	
	def find_distance_and_create_if_empty(courier, dist, earliest_delivery_datetime, cost)
		search_courier = SearchCourier.where(:courier_id => courier.id, :search_id => id).first
		if search_courier.nil?
			search_courier = new_search_courier(courier)
			search_courier.est_distance = dist
			search_courier.est_cost = cost
			search_courier.est_time = earlist_delivery_datetime
			search_courier.save
		end
		search_courier.update_attributes(:est_distance => dist, :est_cost => est_cost, :est_time => earliest_delivery_datetime)
	end
	
	def calc_cost(courier, dist)
		cost_per_distance = courier.cost_per_distance * dist
		est_cost = cost_per_distance + courier.cost_per_distance_per_mass * cost_per_distance * min_mass + courier.cost_per_distance_per_volume * cost_per_distance * min_volume
		est_cost
	end
	
	def find_couriers_within_distance
		pickup_loc = GeoKit::Geocoders::MultiGeocoder.geocode(pickup_address)
		couriers = Courier.within(max_distance, :origin => pickup_loc)
		# create a copy that exists only in memory so .delete does not touch activerecord stuff
		couriers_without_deliveries = couriers.compact
		
		couriers_without_deliveries.each do |courier|
			if courier.deliveries.nil? or courier.deliveries.where(:successfully_delivered => false).first.nil?
				earliest_delivery_datetime = estimate_delivery_datetime(courier, dist)
				if earliest_delivery_datetime > delivery_due
					couriers_without_deliveries.delete(courier)
				else
					cost = calc_cost(courier, courier.distance)
					if cost > max_cost
						couriers_without_deliveries.delete(courier)
					else
						find_distance_and_create_if_empty(courier, courier.distance, earliest_delivery_datetime, cost)
					end
				end
			else
				couriers_without_deliveries.delete(courier)	
			end
		end
		couriers = Courier.all
		courier_with_deliveries = couriers.compact
		couriers_with_deliveries.each do |courier|
			if courier.deliveries.nil? or courier.deliveries.where(:successfully_delivered => false).first.nil?
				couriers_with_deliveries.delete(courier)
			else
				delivery = courier.deliveries.where(:successfully_delivered => false).order('waypoint_order DESC').first
				if delivery.within(max_distance, :origin => pickup_loc)
					earliest_delivery_datetime = estimate_delivery_datetime(courier, delivery.distance)
					if earliest_delivery_datetime > delivery_due
						couriers_with_deliveries.delete(courier)
					else
						cost = calc_cost(courier, courier.distance)
						if cost > max_cost
							couriers_with_deliveries.delete(courier)
						else
							find_distance_and_create_if_empty(courier, delivery.distance, earliest_delivery_datetime, cost)							
						end
					end
				else
					couriers_with_deliveries.delete(courier)
				end
			end
		end
		couriers = couriers_without_deliveries + couriers_with_deliveries
		couriers
	end
	
	def find_couriers(couriers)
	  couriers.find(:all, :conditions => conditions)
	end
	
	def min_volume_conditions
	  ["couriers.avail_volume >= ?", min_volume] unless min_volume.blank?
	end
	
	def min_volume_conditions
	  ["couriers.avail_mass >= ?", min_mass] unless min_mass.blank?
	end
	
	def transport_mode_conditions
	  ["couriers.transport_mode = ?", transport_mode] unless transport_mode.blank?
	end
	
	def conditions
	  [conditions_clauses.join(' AND '), *conditions_options]
	end
	
	def conditions_clauses
	  conditions_parts.map { |condition| condition.first }
	end
	
	def conditions_options
	  conditions_parts.map { |condition| condition[1..-1] }.flatten
	end
	
	def conditions_parts
	  private_methods(false).grep(/_conditions$/).map { |m| send(m) }.compact
	end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # GET /searches
  # GET /searches.xml
  def index
    @searches = Search.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @searches }
    end
  end

  # GET /searches/1
  # GET /searches/1.xml
  def show
    @search = Search.find(params[:id])
    @found_couriers = @search.couriers

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @search }
    end
  end

  # GET /searches/new
  # GET /searches/new.xml
  def new
    @search = Search.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @search }
    end
  end

  # GET /searches/1/edit
  def edit
    @search = Search.find(params[:id])
  end

  # POST /searches
  # POST /searches.xml
  def create
    @search = Search.new(params[:search])

    respond_to do |format|
      if @search.save
        format.html { redirect_to(@search, :notice => 'Search was successfully created.') }
        format.xml  { render :xml => @search, :status => :created, :location => @search }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /searches/1
  # PUT /searches/1.xml
  def update
    @search = Search.find(params[:id])

    respond_to do |format|
      if @search.update_attributes(params[:search])
        format.html { redirect_to(@search, :notice => 'Search was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.xml
  def destroy
    @search = Search.find(params[:id])
    @search.destroy

    respond_to do |format|
      format.html { redirect_to(searches_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :min_volume %><br />
    <%= f.text_field :min_volume %>
  </div>
  <div class="field">
    <%= f.label :min_mass %><br />
    <%= f.text_field :min_mass %>
  </div>
  <div class="field">
    <%= f.label :transport_mode %><br />
    <%= f.select :transport_mode, Courier::TRANSPORT_MODES, :prompt => "Select a tranport mode" %>
  </div>
  <div class="field">
    <%= f.label :total_cost_less_than %><br />
    <%= f.text_field :total_cost_less_than %>
  </div>
  <div class="field">
    <%= f.label :last_coordinate_update_time_greater_than %><br />
    <%= f.datetime_select :last_coordinate_update_time_greater_than %>
  </div>
  <div class="field">
    <%= f.label :max_distance %><br />
    <%= f.select :max_distance, Search::MAX_DISTANCES, :prompt => "Select the max distance between the couriers current location and the pickup address" %>
  </div>
  <div class="field">
    <%= f.label :pickup_address %><br />
    <%= f.text_field :pickup_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<h1>Listing searches</h1>

<table>
  <tr>
    <th>Min volume</th>
    <th>Min mass</th>
    <th>Transport mode</th>
    <th>Total cost less than</th>
    <th>Last coordinate update time greater than</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @searches.each do |search| %>
  <tr>
    <td><%= search.min_volume %></td>
    <td><%= search.min_mass %></td>
    <td><%= search.transport_mode %></td>
    <td><%= search.total_cost_less_than %></td>
    <td><%= search.last_coordinate_update_time_greater_than %></td>
    <td><%= link_to 'Show', search %></td>
    <td><%= link_to 'Edit', edit_search_path(search) %></td>
    <td><%= link_to 'Destroy', search, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<table>
	<tr>
		<td>Max Volume</td>
		<td>Max Mass</td>
		<td>Distance</td>
	</tr>
	<% @found_couriers.each do |courier| %>
		<tr>
			<td><%= courier.max_volume %></td>
			<td><%= courier.max_mass %></td>
			<td><%= courier.distances.first.est_distance %></td>
			<td><%= link_to 'View Courier', courier_path(courier) %></td>
			<td><%= link_to 'New Delivery With This Courier', new_courier_delivery_path(courier, :search_id => @search) %></td>
		</tr>
	<% end %>
</table>
<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>