config/routes.rb
Couriertrack::Application.routes.draw do

  resources :searches, :user_sessions, :courier_sessions, :users
  
  match 'courier_login' => 'courier_sessions#new', :as => :courier_login
  match 'courier_logout' => 'courier_sessions#destroy', :as => :courier_logout
  
  match 'user_login' => 'user_sessions#new', :as => :user_login
  match 'user_logout' => 'user_sessions#destroy', :as => :user_logout

  resources :couriers do
  	resources :deliveries do
  		resources :dropoffs
  		resources :pickups
  	end
  end

end

app/models/dropoff.rb
class Dropoff < ActiveRecord::Base
	acts_as_mappable :default_units => :kms, :auto_geocode=>{:field=>:dropoff_address, :error_message=>'Could not geocode address'}
	belongs_to :delivery
	
	validate :set_coordinates
	validates_presence_of :dropoff_address, :dropoff_name
	validates_datetime :delivery_due, :after => :earliest_delivery_time
	
	def earliest_delivery_time
		
	end
end

app/controllers/dropoffs_controller.rb
class DropoffsController < ApplicationController
  # GET /dropoffs
  # GET /dropoffs.xml
  def index
  	@courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:delivery_id])
    @dropoffs = @delivery.dropoffs.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dropoffs }
    end
  end

  # GET /dropoffs/1
  # GET /dropoffs/1.xml
  def show
  	@courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:delivery_id])
    @dropoff = @delivery.dropoffs.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dropoff }
    end
  end

  # GET /dropoffs/new
  # GET /dropoffs/new.xml
  def new
  	@courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:delivery_id])
    @dropoff = @delivery.dropoffs.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dropoff }
    end
  end

  # GET /dropoffs/1/edit
  def edit
  	@courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:delivery_id])
    @dropoff = @delivery.dropoffs.find(params[:id])
  end

  # POST /dropoffs
  # POST /dropoffs.xml
  def create
  	@courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:delivery_id])
    @dropoff = @delivery.dropoffs.new(params[:dropoff])

    respond_to do |format|
      if @dropoff.save
        format.html { redirect_to(@dropoff, :notice => 'Dropoff was successfully created.') }
        format.xml  { render :xml => @dropoff, :status => :created, :location => @dropoff }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dropoff.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dropoffs/1
  # PUT /dropoffs/1.xml
  def update
  	@courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:delivery_id])
    @dropoff = @delivery.dropoffs.find(params[:id])

    respond_to do |format|
      if @dropoff.update_attributes(params[:dropoff])
        format.html { redirect_to(@dropoff, :notice => 'Dropoff was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dropoff.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dropoffs/1
  # DELETE /dropoffs/1.xml
  def destroy
  	@courier = Courier.find(params[:courier_id])
    @delivery = @courier.deliveries.find(params[:delivery_id])
    @dropoff = @delivery.dropoffs.find(params[:id])
    @dropoff.destroy

    respond_to do |format|
      format.html { redirect_to(dropoffs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/dropoffs_helper.rb
module DropoffsHelper
end

app/views/dropoffs/_form.html.erb
<%= form_for(@dropoff) do |f| %>
  <% if @dropoff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dropoff.errors.count, "error") %> prohibited this dropoff from being saved:</h2>

      <ul>
      <% @dropoff.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dropoff_address %><br />
    <%= f.text_field :dropoff_address %>
  </div>
  <div class="field">
    <%= f.label :dropoff_name %><br />
    <%= f.text_field :dropoff_name %>
  </div>
  <div class="field">
    <%= f.label :dropoff_due %><br />
    <%= f.datetime_select :dropoff_due %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dropoffs/edit.html.erb
<h1>Editing dropoff</h1>

<%= render 'form' %>

<%= link_to 'Show', courier_delivery_dropoff_path(@courier, @delivery, @dropoff) %> |
<%= link_to 'Back', courier_delivery_dropoffs_path %>

app/views/dropoffs/index.html.erb
<h1>Listing dropoffs</h1>

<table>
  <tr>
    <th>Dropoff address</th>
    <th>Dropoff name</th>
    <th>Dropoff due</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dropoffs.each do |dropoff| %>
  <tr>
    <td><%= dropoff.dropoff_address %></td>
    <td><%= dropoff.dropoff_name %></td>
    <td><%= dropoff.dropoff_due %></td>
    <td><%= link_to 'Show', courier_delivery_dropoff_path(@courier, @delivery, dropoff) %></td>
    <td><%= link_to 'Edit', edit_courier_delivery_dropoff_path(@courier, @delivery, dropoff) %></td>
    <td><%= link_to 'Destroy', [@courier, @delivery, dropoff], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dropoff', new_courier_delivery_dropoff_path(@courier, @delivery) %>

app/views/dropoffs/new.html.erb
<h1>New dropoff</h1>

<%= render 'form' %>

<%= link_to 'Back', courier_delivery_dropoffs_path(@courier, @delivery) %>

app/views/dropoffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Dropoff address:</b>
  <%= @dropoff.dropoff_address %>
</p>

<p>
  <b>Dropoff name:</b>
  <%= @dropoff.dropoff_name %>
</p>

<p>
  <b>Dropoff due:</b>
  <%= @dropoff.dropoff_due %>
</p>


<%= link_to 'Edit', edit_courier_delivery_dropoff_path(@courier, @delivery, @dropoff) %> |
<%= link_to 'Back', courier_delivery_dropoffs_path %>